image: mcr.microsoft.com/dotnet/sdk:8.0

variables:
  DOTNET_CLI_TELEMETRY_OPTOUT: "1"
  DOTNET_NOLOGO: "1"
  CONFIGURATION: Release

stages:
  - restore
  - build
  - test

workflow:
  rules:
    # Запуск на пуш в release/main
    - if: '$CI_COMMIT_BRANCH == "release/main"'
      when: always

    # Запуск на MR в release/main
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "release/main"'
      when: always

    # Во всех остальных случаях pipeline не запускается
    - when: never

cache:
  key: nuget
  paths:
    - ~/.nuget/packages/

restore:
  stage: restore
  script:
    - dotnet restore

build:webapp:
  stage: build
  script:
    - dotnet build ControlSystem.MainApp/ControlSystem.MainApp.csproj --no-restore -c $CONFIGURATION
  needs: [restore]

build:tests:
  stage: build
  script:
    - dotnet build ControlSystem.Tests/ControlSystem.Tests.csproj --no-restore -c $CONFIGURATION
  needs: [restore]

test:
  stage: test
  script:
    - dotnet test ControlSystem.Tests/ControlSystem.Tests.csproj --no-build -c $CONFIGURATION
  needs:
    - build:webapp
    - build:tests