apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: minio-barman
  namespace: control-system
spec:
  configuration:
    destinationPath: s3://pg-backups
    endpointURL: http://minio.control-system.svc.cluster.local:9000
    s3Credentials:
      accessKeyId:
        name: minio-secret
        key: access_key
      secretAccessKey:
        name: minio-secret
        key: secret_key
    wal:
      compression: gzip
