apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: controlsystem-pg
  namespace: control-system
spec:
  instances: 3                     # 1 primary + 2 реплики
  imageName: ghcr.io/cloudnative-pg/postgresql:16
  primaryUpdateStrategy: unsupervised

  storage:
    size: 1Gi

  bootstrap:
    initdb:
      database: postgres
      owner: postgres
      secret:
        name: pg-secret

  monitoring:
    enablePodMonitor: false