apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: controlsystem-pg
  namespace: control-system
spec:
  instances: 2                     
  imageName: ghcr.io/cloudnative-pg/postgresql:16
  primaryUpdateStrategy: unsupervised

  storage:
    size: 1Gi

  resources: 
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "1"
      memory: "1.5Gi"

  superuserSecret:
    name: superuser-secret
  
  bootstrap:
    initdb:
      postInitApplicationSQLRefs:
        secretRefs:
          - name: init-db-secret
            key: init-db.sql

  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: minio-barman

  monitoring:
    enablePodMonitor: false