apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: control-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: minio/minio:RELEASE.2025-09-07T16-13-09Z-cpuv1
          args:
            - server
            - /data
            - --console-address
            - ":9001"
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: access_key
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: secret_key
          ports:
            - containerPort: 9000
          volumeMounts:
            - name: minio-data
              mountPath: /data
          resources:
           requests:
             cpu: "250m"
             memory: "512Mi"
           limits:
             cpu: "500m"
             memory: "1Gi"
      volumes:
        - name: minio-data
          persistentVolumeClaim:
            claimName: minio-pvc